### ISSUE TITLE
Broken Delete endpoint, undefined gid

### ISSUE THREAD

**Issue by dianvaltodorov** [catiepg/gopher-client#2]
The delete request sends value 'undefined' for the gopher id resulting in an invalid call to endpoint: '/api/gopher/undefined'

In ordered to verify this I console logged the gopher id in index.js on line 108. 

Can you investigate what happens when the 'Remove Gopher' button from the dialog is clicked?

**Comment by catiepg** [comment]
Sorry, I cannot replicate this, so I will have to guess what the problem is:
1. The REST API does not return an object that has a 'gid' field ;
2. My browsers (Chrome & Safari) are different from your browsers :D ;
3. A problem with the JS part - although I cannot replicate the bug, there might be a problem in the code - I will push a change ASAP and it would be great if you could test it out.

**Comment by dianvaltodorov** [comment]
It was 1. Gopher ecosystem did not comply with the expected schema for the response
